import cirq
from cirq.transformers import *

q = cirq.LineQubit.range(6) 
circuit = cirq.Circuit()


cirq.contrib.acquaintance.AcquaintanceOperation([q[3],q[0]], [3, 0]) 
cirq.contrib.acquaintance.LinearPermutationGate(num_qubits=2, permutation={1: 0, 0: 1}).on(q[4],q[1]) 
circuit.append(cirq.SQRT_ISWAP_INV(q[2], q[1]))
circuit.append(cirq.CNOT(q[3], q[4]).controlled_by(q[0]))
circuit.append(cirq.YYPowGate(exponent=0.006135923151542565).on(q[2], q[0]))
circuit.append(cirq.YYPowGate(exponent=0.09817477042468103).on(q[4], q[3]))
circuit.append(cirq.X(q[4]).controlled_by(q[3]))
circuit.append(cirq.Z(q[0]))
circuit.append(cirq.CSwapGate().on(q[4], q[2], q[0]))
circuit.append(cirq.SQRT_ISWAP(q[2], q[0]))
circuit.append(cirq.ISWAP(q[4], q[1]))
circuit.append(cirq.CCZ(q[3], q[1], q[0]))

cirq.contrib.acquaintance.AcquaintanceOpportunityGate(num_qubits=4).on(q[0],q[2],q[4],q[3]) 
cirq.contrib.acquaintance.CircularShiftGate(shift=1, num_qubits=5).on(q[2],q[0],q[3],q[1],q[4]) 
sub_circuit = cirq.Circuit() 
sub_circuit.append(cirq.CNOT(q[4], q[3]).controlled_by(q[0]))
sub_circuit.append(cirq.MSGate(rads=0.006135923151542565).on(q[3], q[1]).controlled_by(q[0]))
sub_circuit.append(cirq.rz(0.19634954084936207).on(q[0]))
sub_circuit.append(cirq.CCZ(q[4], q[0], q[3]).controlled_by(q[2]))
sub_circuit.append(cirq.T(q[3]))
sub_circuit.append(cirq.H(q[3]).controlled_by(q[0]))
sub_circuit.append(cirq.Y(q[1]))
sub_circuit.append(cirq.CCZ(q[4], q[1], q[0]))
sub_circuit.append(cirq.CCX(q[4], q[2], q[1]))
sub_circuit.append(cirq.T(q[4]).controlled_by(q[0]))
sub_op = cirq.CircuitOperation(sub_circuit.freeze()) 
circuit.append(cirq.measure(q[5], key="c")) 
circuit.append(cirq.measure([q[4],q[1]], key="ca")) 
dc_cond = cirq.BitMaskKeyCondition.create_equal_mask('ca', bitmask=1)
circuit.append(sub_op.with_classical_controls("c", dc_cond)) 

cirq.contrib.acquaintance.AcquaintanceOperation([q[3],q[1],q[4],q[0]], [3, 1, 4, 0]) 
cirq.contrib.acquaintance.AcquaintanceOpportunityGate(num_qubits=2).on(q[1],q[3]) 
cirq.contrib.acquaintance.LinearPermutationGate(num_qubits=3, permutation={2: 1, 1: 2, 0: 0}).on(q[4],q[2],q[3]) 
circuit.append(cirq.ISWAP(q[4], q[0]).controlled_by(q[2]))
circuit.append(cirq.CSwapGate().on(q[4], q[1], q[0]))
circuit.append(cirq.Z(q[1]).controlled_by(q[3]))
circuit.append(cirq.ZPowGate(exponent=0.04908738521234052).on(q[4]).controlled_by(q[3]))
circuit.append(cirq.ZZPowGate(exponent=0.09817477042468103).on(q[3], q[2]))
circuit.append(cirq.CCX(q[4], q[3], q[2]))
circuit.append(cirq.H(q[4]))
circuit.append(cirq.YYPowGate(exponent=0.04908738521234052).on(q[4], q[2]))
circuit.append(cirq.CSwapGate().on(q[1], q[3], q[4]).controlled_by(q[0]))
circuit.append(cirq.Z(q[4]).controlled_by(q[3]))

cirq.contrib.acquaintance.AcquaintanceOpportunityGate(num_qubits=5).on(q[1],q[3],q[2],q[0],q[4]) 
cirq.contrib.acquaintance.CircularShiftGate(shift=1, num_qubits=5).on(q[4],q[3],q[0],q[1],q[2]) 
circuit.append(cirq.measure(q, key="m")) 
circuit = optimize_for_target_gateset(circuit)
circuit = stratified_circuit(circuit)
circuit = merge_single_qubit_moments_to_phxz(circuit)
simulator = cirq.Simulator() 
result = simulator.run(circuit, repetitions=500)
print(result.histogram(key='m'))