from qiskit import QuantumCircuit, QuantumRegister, ClassicalRegister
from qiskit.circuit import Parameter, ParameterVector
from helpers.qiskit_helpers import compare_statevectors, run_on_simulator, run_routing_simulation, run_pass_on_simulator
from pathlib import Path
from math import pi

main_circ = QuantumCircuit(1)
# Adding qregs 
qreg_0 = QuantumRegister(3)
main_circ.add_register(qreg_0)
qreg_3 = QuantumRegister(1)
main_circ.add_register(qreg_3)
# Adding creg resources 
creg_0 = ClassicalRegister(2)
main_circ.add_register(creg_0)
# Adding symbols 
param_0 = Parameter("param_0")
param_1 = Parameter("param_1")
param_2 = Parameter("param_2")

main_circ.cz(qreg_0[1],qreg_3[0])
main_circ.rz(param_2, qreg_0[0])
main_circ.cz(qreg_3[0],qreg_0[1])
main_circ.cz(qreg_0[1],qreg_0[0])
main_circ.cy(qreg_0[1],qreg_0[0])
main_circ.cy(qreg_0[1],0)
main_circ.s(qreg_0[1])
main_circ.cz(qreg_0[1],qreg_3[0])
main_circ.cz(qreg_0[1],qreg_3[0])
main_circ.cy(qreg_0[2],qreg_3[0])
main_circ.s(qreg_0[2])
main_circ.rz(-0.938000, qreg_0[1])
main_circ.s(qreg_3[0])
main_circ.rz(param_2, qreg_3[0])
main_circ.s(0)
main_circ.rz(0.853000, qreg_0[2])
main_circ.rz(param_2, qreg_0[2])
main_circ.s(0)
main_circ.rz(0.775000, qreg_3[0])
main_circ.s(qreg_0[0])
main_circ.rz(-0.365000, qreg_0[2])
main_circ.cy(qreg_3[0],qreg_0[0])
main_circ.s(qreg_3[0])
main_circ.cz(qreg_0[0],qreg_3[0])
main_circ.s(qreg_0[0])
main_circ.s(qreg_3[0])
main_circ.cz(qreg_0[2],qreg_0[0])
main_circ.s(qreg_0[0])
main_circ.rz(-0.180000, qreg_0[2])
main_circ.rz(param_2, qreg_0[2])
main_circ.rz(param_1, qreg_0[1])
main_circ.rz(0.655000, 0)
main_circ.rz(param_2, qreg_0[0])
main_circ.cy(qreg_0[2],qreg_3[0])
main_circ.s(qreg_3[0])
main_circ.rz(0.299000, qreg_3[0])
main_circ.rz(param_0, qreg_3[0])
main_circ.s(qreg_3[0])
main_circ.s(qreg_0[0])
main_circ.s(0)
main_circ.rz(param_0, 0)
main_circ.cy(qreg_0[2],qreg_0[0])
main_circ.cy(qreg_0[0],qreg_3[0])
main_circ.cz(qreg_3[0],qreg_0[2])
main_circ.cy(qreg_3[0],qreg_0[1])
main_circ.cz(qreg_0[2],qreg_0[0])
main_circ.cz(0,qreg_0[1])
main_circ.s(qreg_0[1])
main_circ.s(0)
main_circ.cz(qreg_0[1],0)
main_circ.cy(qreg_0[2],qreg_0[1])
main_circ.cy(qreg_3[0],qreg_0[1])
main_circ.s(qreg_3[0])
main_circ.s(qreg_0[0])
main_circ.rz(-0.831000, qreg_3[0])
main_circ.cz(qreg_0[2],qreg_0[1])
main_circ.rz(param_0, 0)
main_circ.s(qreg_3[0])
main_circ.rz(param_1, qreg_0[0])
bindings = {param_0: -0.484000, param_1: 0.046000, param_2: 0.064000, }
main_circ = main_circ.assign_parameters(bindings)

print(Path(__file__).name, " results:")
compare_statevectors(main_circ, "CommutativeInverseCancellation")
