from qiskit import QuantumCircuit, QuantumRegister, ClassicalRegister
from qiskit.circuit import Parameter, ParameterVector
from helpers.qiskit_helpers import compare_statevectors, run_on_simulator, run_routing_simulation, run_pass_on_simulator
from pathlib import Path
from math import pi

subcirc0 = QuantumCircuit(0)
# Adding qregs 
qreg_0 = QuantumRegister(1)
subcirc0.add_register(qreg_0)
qreg_1 = QuantumRegister(1)
subcirc0.add_register(qreg_1)
qreg_2 = QuantumRegister(1)
subcirc0.add_register(qreg_2)
qreg_3 = QuantumRegister(1)
subcirc0.add_register(qreg_3)
# Adding creg resources 
subcirc0.cx(qreg_0[0],qreg_2[0])
subcirc0.ry(-0.532000, qreg_1[0])
subcirc0.y(qreg_3[0])
subcirc0.y(qreg_1[0])
subcirc0.z(qreg_2[0])
subcirc0 = subcirc0.to_gate().control(2)

main_circ = QuantumCircuit(4)
# Adding qregs 
# Adding creg resources 
creg_0 = ClassicalRegister(2)
main_circ.add_register(creg_0)
# Adding symbols 
param_0 = Parameter("param_0")
param_1 = Parameter("param_1")
param_2 = Parameter("param_2")
param_3 = Parameter("param_3")

main_circ.ry(-0.551000, 1)
main_circ.cx(2,0)
main_circ.cx(2,0)
main_circ.z(3)
main_circ.z(3)
main_circ.y(0)
main_circ.z(1)
main_circ.cx(1,2)
main_circ.cx(2,1)
main_circ.cx(1,2)
main_circ.ry(-0.374000, 0)
main_circ.z(2)
main_circ.ry(param_2, 2)
main_circ.z(0)
main_circ.z(1)
main_circ.cx(3,2)
main_circ.z(1)
main_circ.z(0)
main_circ.y(0)
main_circ.y(0)
main_circ.ry(param_3, 0)
main_circ.cx(1,3)
main_circ.z(1)
main_circ.y(3)
main_circ.z(0)
main_circ.cx(0,1)
main_circ.z(3)
main_circ.ry(param_2, 0)
main_circ.y(1)
main_circ.z(0)
main_circ.cx(3,0)
main_circ.ry(param_1, 2)
main_circ.cx(0,2)
main_circ.z(0)
main_circ.cx(3,2)
main_circ.cx(2,1)
main_circ.y(3)
main_circ.cx(3,2)
main_circ.z(3)
main_circ.ry(0.138000, 0)
main_circ.ry(param_3, 0)
main_circ.y(0)
main_circ.cx(3,1)
main_circ.cx(3,0)
main_circ.cx(1,3)
main_circ.cx(3,1)
main_circ.z(2)
main_circ.z(3)
main_circ.cx(0,2)
main_circ.y(2)
main_circ.y(2)
main_circ.cx(3,1)
main_circ.cx(3,2)
main_circ.z(0)
main_circ.ry(param_0, 2)
main_circ.y(1)
main_circ.ry(param_0, 1)
main_circ.z(2)
main_circ.cx(1,3)
bindings = {param_0: 0.553000, param_1: 0.504000, param_2: 0.553000, param_3: 0.059000, }
main_circ = main_circ.assign_parameters(bindings)

print(Path(__file__).name, " results:")
main_circ.measure_active()
run_routing_simulation(main_circ, "1938")
