from qiskit import QuantumCircuit, QuantumRegister, ClassicalRegister
from qiskit.circuit import Parameter, ParameterVector
from helpers.qiskit_helpers import compare_statevectors, run_on_simulator, run_routing_simulation, run_pass_on_simulator
from pathlib import Path
from math import pi

main_circ = QuantumCircuit(4)
# Adding qregs 
# Adding creg resources 
creg_0 = ClassicalRegister(1)
main_circ.add_register(creg_0)
creg_1 = ClassicalRegister(1)
main_circ.add_register(creg_1)
# Adding symbols 
param_0 = Parameter("param_0")
param_1 = Parameter("param_1")

main_circ.ry(param_0, 0)
main_circ.cz(0,1)
main_circ.ry(-0.402000, 2)
main_circ.ry(0.485000, 3)
main_circ.rx(param_1, 0)
main_circ.x(1)
main_circ.cz(3,2)
main_circ.ry(-0.776000, 3)
main_circ.rx(-0.104000, 0)
main_circ.cz(0,3)
main_circ.rx(param_0, 0)
main_circ.x(1)
main_circ.x(2)
main_circ.cz(2,1)
main_circ.rx(param_0, 3)
main_circ.cz(0,3)
main_circ.rx(param_0, 3)
main_circ.cz(0,3)
main_circ.ry(param_0, 2)
main_circ.cz(3,2)
main_circ.ry(param_1, 3)
main_circ.ry(param_1, 2)
main_circ.ry(-0.238000, 3)
main_circ.cz(3,2)
main_circ.x(0)
main_circ.cz(0,2)
main_circ.ry(param_1, 3)
main_circ.cz(3,1)
main_circ.x(1)
main_circ.x(3)
main_circ.x(0)
main_circ.ry(param_1, 2)
main_circ.cz(2,1)
main_circ.cz(1,3)
main_circ.cz(2,1)
main_circ.ry(param_1, 1)
main_circ.ry(param_0, 0)
main_circ.ry(0.730000, 0)
main_circ.rx(-0.129000, 3)
main_circ.x(3)
main_circ.ry(param_0, 2)
main_circ.cz(1,2)
main_circ.ry(0.417000, 1)
main_circ.ry(0.397000, 3)
main_circ.rx(-0.835000, 2)
bindings = {param_0: 0.283000, param_1: 0.202000, }
main_circ = main_circ.assign_parameters(bindings)

print(Path(__file__).name, " results:")
compare_statevectors(main_circ, "TemplateOptimization")
