from qiskit import QuantumCircuit, QuantumRegister, ClassicalRegister
from qiskit.circuit import Parameter, ParameterVector
from helpers.qiskit_helpers import compare_statevectors, run_on_simulator, run_routing_simulation, run_pass_on_simulator
from pathlib import Path
from math import pi

main_circ = QuantumCircuit(4)
# Adding qregs 
qreg_0 = QuantumRegister(2)
main_circ.add_register(qreg_0)
# Adding creg resources 
creg_0 = ClassicalRegister(1)
main_circ.add_register(creg_0)
creg_1 = ClassicalRegister(1)
main_circ.add_register(creg_1)
# Adding symbols 
param_0 = Parameter("param_0")
param_1 = Parameter("param_1")
param_2 = Parameter("param_2")

main_circ.u(param_2,param_2,param_0, 1)
main_circ.h(2)
main_circ.z(3)
main_circ.u(param_0,param_0,-0.940000, qreg_0[1])
main_circ.u(0,0,-0.280000, qreg_0[0])
main_circ.u(param_2,0,0.236000, 1)
main_circ.z(0)
main_circ.cz(1,qreg_0[1])
main_circ.z(2)
main_circ.h(2)
main_circ.cz(0,qreg_0[1])
main_circ.z(qreg_0[0])
main_circ.cz(0,3)
main_circ.u(0,0,0.671000, qreg_0[0])
main_circ.z(qreg_0[1])
main_circ.z(qreg_0[0])
main_circ.cz(qreg_0[0],qreg_0[1])
main_circ.u(0,0,param_0, qreg_0[0])
main_circ.cz(2,3)
main_circ.z(qreg_0[0])
main_circ.u(param_1,param_1,param_0, qreg_0[0])
main_circ.u(0,0,-0.219000, qreg_0[0])
main_circ.cz(qreg_0[0],0)
main_circ.u(0,param_2,-0.071000, 2)
main_circ.z(1)
main_circ.cz(qreg_0[0],1)
main_circ.z(1)
main_circ.u(param_0,0,param_1, 0)
main_circ.cz(2,0)
main_circ.cz(0,qreg_0[0])
main_circ.cz(2,qreg_0[0])
main_circ.cz(2,qreg_0[1])
main_circ.cz(3,qreg_0[0])
main_circ.h(1)
main_circ.h(3)
main_circ.h(qreg_0[1])
main_circ.h(3)
main_circ.h(2)
main_circ.cz(2,3)
main_circ.u(0,param_1,param_2, 0)
bindings = {param_0: -0.266000, param_1: -0.642000, param_2: -0.657000, }
main_circ = main_circ.assign_parameters(bindings)

print(Path(__file__).name, " results:")
main_circ.measure_active()
run_routing_simulation(main_circ, "1832")
