from qiskit import QuantumCircuit, QuantumRegister, ClassicalRegister
from qiskit.circuit import Parameter, ParameterVector
from helpers.qiskit_helpers import compare_statevectors, run_on_simulator, run_routing_simulation, run_pass_on_simulator
from pathlib import Path
from math import pi

main_circ = QuantumCircuit(0)
# Adding qregs 
qreg_0 = QuantumRegister(2)
main_circ.add_register(qreg_0)
qreg_2 = QuantumRegister(1)
main_circ.add_register(qreg_2)
qreg_3 = QuantumRegister(1)
main_circ.add_register(qreg_3)
# Adding creg resources 
creg_0 = ClassicalRegister(1)
main_circ.add_register(creg_0)
creg_1 = ClassicalRegister(1)
main_circ.add_register(creg_1)
# Adding symbols 
param_0 = Parameter("param_0")

main_circ.cx(qreg_0[0],qreg_2[0])
main_circ.cx(qreg_0[0],qreg_0[1])
main_circ.x(qreg_3[0])
main_circ.x(qreg_3[0])
main_circ.x(qreg_3[0])
main_circ.cx(qreg_0[0],qreg_0[1])
main_circ.x(qreg_0[1])
main_circ.cx(qreg_2[0],qreg_0[0])
main_circ.cx(qreg_0[0],qreg_3[0])
main_circ.x(qreg_0[1])
main_circ.cy(qreg_0[1],qreg_3[0])
main_circ.rz(param_0, qreg_2[0])
main_circ.cy(qreg_0[1],qreg_3[0])
main_circ.rz(-0.633000, qreg_0[0])
main_circ.cx(qreg_0[0],qreg_2[0])
main_circ.x(qreg_0[0])
main_circ.rz(param_0, qreg_0[0])
main_circ.x(qreg_0[0])
main_circ.cx(qreg_0[0],qreg_0[1])
main_circ.cy(qreg_3[0],qreg_2[0])
main_circ.rz(-0.850000, qreg_0[1])
main_circ.rz(param_0, qreg_2[0])
main_circ.rz(param_0, qreg_3[0])
main_circ.rz(param_0, qreg_0[0])
main_circ.x(qreg_2[0])
main_circ.cy(qreg_3[0],qreg_2[0])
main_circ.rz(-0.014000, qreg_0[1])
main_circ.rz(param_0, qreg_0[0])
main_circ.x(qreg_0[0])
main_circ.cy(qreg_2[0],qreg_0[0])
main_circ.cx(qreg_0[1],qreg_2[0])
main_circ.x(qreg_0[0])
main_circ.cy(qreg_3[0],qreg_0[0])
main_circ.cy(qreg_0[1],qreg_2[0])
main_circ.cy(qreg_0[0],qreg_0[1])
main_circ.cx(qreg_0[0],qreg_0[1])
main_circ.rz(param_0, qreg_0[1])
main_circ.cy(qreg_3[0],qreg_0[1])
main_circ.cx(qreg_0[0],qreg_3[0])
main_circ.x(qreg_3[0])
main_circ.cx(qreg_0[0],qreg_0[1])
main_circ.cy(qreg_0[0],qreg_2[0])
main_circ.x(qreg_0[0])
main_circ.cy(qreg_2[0],qreg_3[0])
main_circ.cx(qreg_3[0],qreg_0[1])
main_circ.cy(qreg_0[0],qreg_0[1])
main_circ.cx(qreg_0[0],qreg_0[1])
main_circ.cx(qreg_0[1],qreg_2[0])
main_circ.cy(qreg_0[0],qreg_3[0])
main_circ.x(qreg_0[1])
main_circ.rz(-0.199000, qreg_2[0])
main_circ.x(qreg_0[0])
bindings = {param_0: 0.857000, }
main_circ = main_circ.assign_parameters(bindings)

print(Path(__file__).name, " results:")
compare_statevectors(main_circ, "InverseCancellation")
