from qiskit import QuantumCircuit, QuantumRegister, ClassicalRegister
from qiskit.circuit import Parameter, ParameterVector
from helpers.qiskit_helpers import compare_statevectors, run_on_simulator, run_routing_simulation, run_pass_on_simulator
from pathlib import Path
from math import pi

main_circ = QuantumCircuit(2)
# Adding qregs 
qreg_0 = QuantumRegister(4)
main_circ.add_register(qreg_0)
# Adding creg resources 
creg_0 = ClassicalRegister(1)
main_circ.add_register(creg_0)
creg_1 = ClassicalRegister(1)
main_circ.add_register(creg_1)
# Adding symbols 
param_0 = Parameter("param_0")
param_1 = Parameter("param_1")
param_2 = Parameter("param_2")
param_3 = Parameter("param_3")

main_circ.cy(qreg_0[3],qreg_0[0])
main_circ.z(qreg_0[3])
main_circ.h(qreg_0[0])
main_circ.cy(qreg_0[1],0)
main_circ.h(qreg_0[3])
main_circ.rz(param_1, 1)
main_circ.cy(0,1)
main_circ.rz(-0.612000, qreg_0[1])
main_circ.h(qreg_0[1])
main_circ.cy(qreg_0[1],qreg_0[3])
main_circ.z(qreg_0[1])
main_circ.z(0)
main_circ.rz(param_0, 1)
main_circ.cy(qreg_0[0],qreg_0[2])
main_circ.rz(0.009000, qreg_0[3])
main_circ.rz(param_1, 0)
main_circ.z(qreg_0[2])
main_circ.z(qreg_0[2])
main_circ.rz(-0.893000, qreg_0[2])
main_circ.cy(0,qreg_0[2])
main_circ.z(0)
main_circ.h(qreg_0[0])
main_circ.cy(0,qreg_0[0])
main_circ.cy(1,qreg_0[1])
main_circ.rz(0.953000, qreg_0[0])
main_circ.rz(-0.266000, qreg_0[2])
main_circ.h(qreg_0[0])
main_circ.rz(param_2, qreg_0[1])
main_circ.z(qreg_0[0])
main_circ.z(0)
main_circ.rz(param_2, 0)
main_circ.cy(qreg_0[1],qreg_0[0])
main_circ.h(0)
main_circ.z(1)
main_circ.rz(param_3, 1)
main_circ.rz(param_2, 1)
main_circ.h(qreg_0[2])
main_circ.z(qreg_0[2])
main_circ.rz(param_0, qreg_0[0])
main_circ.cy(1,qreg_0[2])
main_circ.z(1)
main_circ.cy(qreg_0[1],qreg_0[2])
main_circ.cy(qreg_0[2],qreg_0[1])
main_circ.cy(0,qreg_0[2])
main_circ.cy(qreg_0[2],1)
main_circ.cy(qreg_0[3],qreg_0[2])
main_circ.cy(qreg_0[0],qreg_0[2])
main_circ.cy(qreg_0[0],0)
main_circ.rz(-0.681000, 1)
main_circ.h(0)
main_circ.cy(qreg_0[2],qreg_0[3])
main_circ.z(qreg_0[1])
main_circ.h(qreg_0[3])
main_circ.z(qreg_0[1])
main_circ.cy(qreg_0[3],0)
main_circ.rz(-0.518000, qreg_0[0])
main_circ.h(0)
main_circ.h(1)
bindings = {param_0: -0.716000, param_1: 0.857000, param_2: -0.001000, param_3: 0.666000, }
main_circ = main_circ.assign_parameters(bindings)

print(Path(__file__).name, " results:")
main_circ.measure_active()
run_routing_simulation(main_circ, "1650")
