from qiskit import QuantumCircuit, QuantumRegister, ClassicalRegister
from qiskit.circuit import Parameter, ParameterVector
from helpers.qiskit_helpers import compare_statevectors, run_on_simulator, run_routing_simulation, run_pass_on_simulator
from pathlib import Path
from math import pi

main_circ = QuantumCircuit(4)
# Adding qregs 
qreg_0 = QuantumRegister(2)
main_circ.add_register(qreg_0)
# Adding creg resources 
creg_0 = ClassicalRegister(2)
main_circ.add_register(creg_0)
# Adding symbols 
param_0 = Parameter("param_0")
param_1 = Parameter("param_1")
param_2 = Parameter("param_2")
param_3 = Parameter("param_3")

main_circ.cx(2,1)
main_circ.y(2)
main_circ.u(param_3,param_3,param_0, 0)
main_circ.cx(qreg_0[0],2)
main_circ.y(qreg_0[0])
main_circ.u(param_2,param_0,param_1, 3)
main_circ.cx(1,0)
main_circ.u(param_3,0,param_2, qreg_0[0])
main_circ.x(3)
main_circ.y(0)
main_circ.cx(3,qreg_0[0])
main_circ.x(3)
main_circ.u(param_3,param_0,0.004000, qreg_0[1])
main_circ.x(3)
main_circ.x(2)
main_circ.u(0,0,-0.082000, qreg_0[1])
main_circ.x(qreg_0[1])
main_circ.u(param_3,0,param_1, 1)
main_circ.x(qreg_0[1])
main_circ.u(param_0,0,param_2, 2)
main_circ.x(3)
main_circ.x(0)
main_circ.cx(0,2)
main_circ.y(qreg_0[0])
main_circ.cx(qreg_0[1],0)
main_circ.y(2)
main_circ.x(0)
main_circ.x(3)
main_circ.x(qreg_0[1])
main_circ.y(qreg_0[1])
main_circ.cx(qreg_0[0],2)
main_circ.x(qreg_0[0])
main_circ.u(0,0,-0.124000, 3)
main_circ.cx(3,1)
main_circ.cx(qreg_0[1],2)
main_circ.cx(3,0)
main_circ.cx(qreg_0[0],2)
main_circ.cx(qreg_0[0],qreg_0[1])
main_circ.cx(qreg_0[1],2)
main_circ.cx(1,qreg_0[1])
main_circ.u(param_0,0,param_0, 2)
main_circ.x(qreg_0[0])
main_circ.u(0,0,0.762000, qreg_0[1])
main_circ.y(2)
main_circ.y(qreg_0[0])
main_circ.cx(qreg_0[0],3)
main_circ.u(param_3,param_2,0.198000, qreg_0[1])
bindings = {param_0: -0.825000, param_1: -0.819000, param_2: -0.023000, param_3: 0.793000, }
main_circ = main_circ.assign_parameters(bindings)

print(Path(__file__).name, " results:")
main_circ.measure_active()
run_routing_simulation(main_circ, "403")
