from qiskit import QuantumCircuit, QuantumRegister, ClassicalRegister
from qiskit.circuit import Parameter, ParameterVector
from helpers.qiskit_helpers import compare_statevectors, run_on_simulator, run_routing_simulation, run_pass_on_simulator
from pathlib import Path
from math import pi

main_circ = QuantumCircuit(4)
# Adding qregs 
qreg_0 = QuantumRegister(2)
main_circ.add_register(qreg_0)
# Adding creg resources 
creg_0 = ClassicalRegister(2)
main_circ.add_register(creg_0)
# Adding symbols 
param_0 = Parameter("param_0")
param_1 = Parameter("param_1")
param_2 = Parameter("param_2")
param_3 = Parameter("param_3")
param_4 = Parameter("param_4")
param_5 = Parameter("param_5")

main_circ.y(2)
main_circ.rz(-0.809000, 3)
main_circ.x(1)
main_circ.z(2)
main_circ.rz(param_1, 3)
main_circ.y(0)
main_circ.x(1)
main_circ.x(qreg_0[1])
main_circ.y(qreg_0[1])
main_circ.y(qreg_0[0])
main_circ.y(2)
main_circ.x(1)
main_circ.z(qreg_0[0])
main_circ.y(1)
main_circ.x(3)
main_circ.rz(0.325000, 0)
main_circ.rz(param_3, qreg_0[0])
main_circ.x(1)
main_circ.x(0)
main_circ.x(2)
main_circ.y(qreg_0[0])
main_circ.y(0)
main_circ.rz(param_1, qreg_0[1])
main_circ.x(qreg_0[1])
main_circ.y(qreg_0[1])
main_circ.rz(param_1, 3)
main_circ.y(1)
main_circ.rz(param_1, 2)
main_circ.z(qreg_0[0])
main_circ.z(3)
main_circ.x(qreg_0[1])
main_circ.x(qreg_0[0])
main_circ.rz(param_0, 0)
main_circ.rz(-0.829000, 1)
main_circ.rz(param_3, 2)
main_circ.x(1)
main_circ.y(qreg_0[1])
main_circ.y(2)
main_circ.x(qreg_0[1])
main_circ.rz(-0.796000, 1)
main_circ.y(1)
main_circ.y(3)
main_circ.x(2)
main_circ.y(qreg_0[1])
main_circ.y(0)
main_circ.rz(param_3, 1)
main_circ.y(qreg_0[1])
main_circ.x(0)
main_circ.x(qreg_0[1])
main_circ.z(qreg_0[0])
main_circ.x(2)
main_circ.x(0)
main_circ.y(qreg_0[0])
main_circ.y(1)
main_circ.x(0)
main_circ.x(qreg_0[0])
bindings = {param_0: -0.176000, param_1: -0.970000, param_3: 0.188000, }
main_circ = main_circ.assign_parameters(bindings)

print(Path(__file__).name, " results:")
compare_statevectors(main_circ, "Collect2qBlocks")
