from qiskit import QuantumCircuit, QuantumRegister, ClassicalRegister
from qiskit.circuit import Parameter, ParameterVector
from helpers.qiskit_helpers import compare_statevectors, run_on_simulator, run_routing_simulation, run_pass_on_simulator
from pathlib import Path
from math import pi

main_circ = QuantumCircuit(4)
# Adding qregs 
qreg_0 = QuantumRegister(1)
main_circ.add_register(qreg_0)
# Adding creg resources 
creg_0 = ClassicalRegister(2)
main_circ.add_register(creg_0)
# Adding symbols 
param_0 = Parameter("param_0")
param_1 = Parameter("param_1")

main_circ.cx(3,0)
main_circ.rz(-0.980000, 1)
main_circ.cx(0,1)
main_circ.h(0)
main_circ.cx(3,qreg_0[0])
main_circ.rz(param_0, 1)
main_circ.ry(-0.676000, 1)
main_circ.cx(qreg_0[0],2)
main_circ.h(2)
main_circ.ry(param_0, 1)
main_circ.cx(2,1)
main_circ.rz(param_0, 1)
main_circ.h(3)
main_circ.h(3)
main_circ.rz(param_1, 2)
main_circ.cx(1,3)
main_circ.ry(0.116000, 0)
main_circ.h(0)
main_circ.h(1)
main_circ.cx(0,2)
main_circ.ry(-0.382000, qreg_0[0])
main_circ.ry(param_1, 0)
main_circ.rz(-0.142000, qreg_0[0])
main_circ.h(qreg_0[0])
main_circ.cx(0,2)
main_circ.h(2)
main_circ.rz(param_1, 0)
main_circ.h(3)
main_circ.ry(-0.243000, 1)
main_circ.h(3)
main_circ.cx(1,0)
main_circ.cx(2,0)
main_circ.cx(2,0)
main_circ.cx(2,0)
main_circ.h(1)
main_circ.cx(0,2)
main_circ.cx(2,qreg_0[0])
main_circ.cx(2,1)
main_circ.ry(param_0, qreg_0[0])
main_circ.ry(param_0, 1)
main_circ.rz(0.419000, qreg_0[0])
main_circ.h(2)
bindings = {param_0: -0.284000, param_1: 0.906000, }
main_circ = main_circ.assign_parameters(bindings)

print(Path(__file__).name, " results:")
main_circ.measure_active()
run_routing_simulation(main_circ, "1428")
