from qiskit import QuantumCircuit, QuantumRegister, ClassicalRegister
from qiskit.circuit import Parameter, ParameterVector
from helpers.qiskit_helpers import compare_statevectors, run_on_simulator, run_routing_simulation, run_pass_on_simulator
from pathlib import Path
from math import pi

main_circ = QuantumCircuit(4)
# Adding qregs 
qreg_0 = QuantumRegister(2)
main_circ.add_register(qreg_0)
# Adding creg resources 
creg_0 = ClassicalRegister(1)
main_circ.add_register(creg_0)
creg_1 = ClassicalRegister(1)
main_circ.add_register(creg_1)
# Adding symbols 
param_0 = Parameter("param_0")

main_circ.cy(qreg_0[1],2)
main_circ.cy(qreg_0[1],2)
main_circ.rz(-0.567000, qreg_0[1])
main_circ.rz(param_0, qreg_0[1])
main_circ.rz(-0.289000, qreg_0[1])
main_circ.h(0)
main_circ.h(qreg_0[0])
main_circ.cy(qreg_0[1],qreg_0[0])
main_circ.s(0)
main_circ.s(1)
main_circ.cy(0,qreg_0[1])
main_circ.cy(qreg_0[0],2)
main_circ.rz(param_0, 3)
main_circ.cy(qreg_0[1],qreg_0[0])
main_circ.s(1)
main_circ.h(0)
main_circ.h(3)
main_circ.cy(1,qreg_0[1])
main_circ.h(3)
main_circ.cy(qreg_0[1],2)
main_circ.s(qreg_0[0])
main_circ.s(qreg_0[1])
main_circ.cy(qreg_0[1],3)
main_circ.h(qreg_0[0])
main_circ.cy(0,2)
main_circ.h(1)
main_circ.h(1)
main_circ.s(qreg_0[1])
main_circ.rz(param_0, 0)
main_circ.rz(param_0, 2)
main_circ.cy(qreg_0[1],3)
main_circ.cy(1,qreg_0[1])
main_circ.s(qreg_0[0])
main_circ.h(qreg_0[1])
main_circ.cy(2,1)
main_circ.h(qreg_0[0])
main_circ.cy(1,qreg_0[1])
main_circ.h(1)
main_circ.s(2)
main_circ.s(2)
main_circ.cy(3,qreg_0[1])
main_circ.rz(0.978000, 1)
bindings = {param_0: -0.033000, }
main_circ = main_circ.assign_parameters(bindings)

print(Path(__file__).name, " results:")
main_circ.measure_active()
run_routing_simulation(main_circ, "1238")
