from qiskit import QuantumCircuit, QuantumRegister, ClassicalRegister
from qiskit.circuit import Parameter, ParameterVector
from helpers.qiskit_helpers import compare_statevectors, run_on_simulator, run_routing_simulation, run_pass_on_simulator
from pathlib import Path
from math import pi

main_circ = QuantumCircuit(1)
# Adding qregs 
qreg_0 = QuantumRegister(1)
main_circ.add_register(qreg_0)
qreg_1 = QuantumRegister(2)
main_circ.add_register(qreg_1)
qreg_3 = QuantumRegister(1)
main_circ.add_register(qreg_3)
# Adding creg resources 
creg_0 = ClassicalRegister(2)
main_circ.add_register(creg_0)
# Adding symbols 
param_0 = Parameter("param_0")
param_1 = Parameter("param_1")

main_circ.x(qreg_0[0])
main_circ.x(qreg_1[0])
main_circ.cz(qreg_0[0],qreg_1[1])
main_circ.cy(qreg_3[0],qreg_1[1])
main_circ.z(qreg_3[0])
main_circ.cz(qreg_1[0],qreg_3[0])
main_circ.cy(0,qreg_1[1])
main_circ.cz(qreg_1[0],qreg_1[1])
main_circ.cz(qreg_3[0],qreg_0[0])
main_circ.x(qreg_1[1])
main_circ.cy(qreg_3[0],qreg_1[1])
main_circ.cy(qreg_1[0],qreg_1[1])
main_circ.cy(qreg_3[0],0)
main_circ.cy(qreg_1[1],qreg_3[0])
main_circ.z(qreg_1[1])
main_circ.cy(0,qreg_0[0])
main_circ.cz(qreg_1[1],qreg_1[0])
main_circ.cz(qreg_3[0],qreg_0[0])
main_circ.z(qreg_1[1])
main_circ.cz(0,qreg_1[1])
main_circ.cy(qreg_1[0],qreg_1[1])
main_circ.x(qreg_1[1])
main_circ.cy(qreg_1[1],qreg_3[0])
main_circ.z(qreg_3[0])
main_circ.cz(0,qreg_1[0])
main_circ.x(qreg_1[1])
main_circ.z(qreg_1[0])
main_circ.z(qreg_3[0])
main_circ.x(qreg_3[0])
main_circ.x(qreg_1[0])
main_circ.z(qreg_1[1])
main_circ.z(0)
main_circ.cy(qreg_1[1],0)
main_circ.x(qreg_1[0])
main_circ.cy(qreg_3[0],qreg_1[0])
main_circ.cy(qreg_1[1],qreg_3[0])
main_circ.z(qreg_1[1])
main_circ.x(qreg_3[0])
main_circ.cy(qreg_0[0],qreg_3[0])
main_circ.cz(qreg_0[0],qreg_1[0])
main_circ.cz(qreg_1[1],0)
main_circ.x(qreg_1[1])
main_circ.z(qreg_3[0])
main_circ.z(qreg_3[0])
main_circ.cz(qreg_1[1],qreg_3[0])
main_circ.cy(qreg_0[0],qreg_1[0])
main_circ.cy(qreg_1[1],qreg_3[0])
main_circ.x(qreg_3[0])
main_circ.x(0)
main_circ.x(qreg_1[0])
main_circ.cy(qreg_1[1],qreg_3[0])
main_circ.z(qreg_1[1])
main_circ.x(qreg_1[0])
main_circ.z(0)
main_circ.cy(qreg_0[0],0)
main_circ.x(qreg_1[1])
main_circ.x(qreg_1[1])
main_circ.z(qreg_1[0])
main_circ.cy(qreg_1[0],qreg_0[0])
main_circ.z(qreg_0[0])
bindings = {}
main_circ = main_circ.assign_parameters(bindings)

print(Path(__file__).name, " results:")
compare_statevectors(main_circ, "ResetAfterMeasureSimplification")
