from qiskit import QuantumCircuit, QuantumRegister, ClassicalRegister
from qiskit.circuit import Parameter, ParameterVector
from helpers.qiskit_helpers import compare_statevectors, run_on_simulator, run_routing_simulation, run_pass_on_simulator
from pathlib import Path
from math import pi

subcirc0 = QuantumCircuit(0)
# Adding qregs 
qreg_0 = QuantumRegister(2)
subcirc0.add_register(qreg_0)
qreg_2 = QuantumRegister(1)
subcirc0.add_register(qreg_2)
qreg_3 = QuantumRegister(1)
subcirc0.add_register(qreg_3)
# Adding creg resources 
subcirc0.cz(qreg_2[0],qreg_0[1])
subcirc0.cy(qreg_3[0],qreg_0[1])
subcirc0.cy(qreg_2[0],qreg_3[0])
subcirc0.y(qreg_2[0])
subcirc0.y(qreg_0[1])
subcirc0.cz(qreg_0[0],qreg_2[0])
subcirc0 = subcirc0.to_gate().control(3)

main_circ = QuantumCircuit(2)
# Adding qregs 
qreg_0 = QuantumRegister(4)
main_circ.add_register(qreg_0)
# Adding creg resources 
creg_0 = ClassicalRegister(1)
main_circ.add_register(creg_0)
creg_1 = ClassicalRegister(1)
main_circ.add_register(creg_1)
# Adding symbols 
param_0 = Parameter("param_0")
param_1 = Parameter("param_1")

main_circ.cz(qreg_0[0],qreg_0[2])
main_circ.rx(param_0, 1)
main_circ.cz(qreg_0[2],0)
main_circ.y(1)
main_circ.cz(1,qreg_0[2])
main_circ.y(qreg_0[2])
main_circ.cy(qreg_0[2],qreg_0[1])
main_circ.cy(qreg_0[2],qreg_0[1])
main_circ.cz(0,qreg_0[3])
main_circ.y(qreg_0[0])
main_circ.rx(0.248000, qreg_0[1])
main_circ.rx(param_1, 1)
main_circ.rx(param_1, 1)
main_circ.y(qreg_0[1])
main_circ.cz(qreg_0[0],1)
main_circ.rx(0.351000, qreg_0[2])
main_circ.cy(qreg_0[2],0)
main_circ.y(0)
main_circ.cz(qreg_0[0],1)
main_circ.rx(-0.265000, qreg_0[1])
main_circ.rx(0.247000, qreg_0[2])
main_circ.y(qreg_0[1])
main_circ.y(qreg_0[3])
main_circ.cz(qreg_0[3],1)
main_circ.y(qreg_0[2])
main_circ.cz(qreg_0[2],0)
main_circ.cy(qreg_0[1],qreg_0[3])
main_circ.cz(qreg_0[3],0)
main_circ.cy(qreg_0[3],qreg_0[2])
main_circ.rx(-0.295000, qreg_0[0])
main_circ.y(0)
main_circ.y(qreg_0[2])
main_circ.rx(0.431000, 0)
main_circ.rx(0.528000, 0)
main_circ.cz(qreg_0[3],qreg_0[1])
main_circ.cz(qreg_0[2],qreg_0[0])
main_circ.cy(qreg_0[2],qreg_0[3])
main_circ.cy(qreg_0[1],qreg_0[0])
main_circ.rx(param_0, 1)
main_circ.y(qreg_0[3])
main_circ.cy(qreg_0[2],qreg_0[1])
main_circ.cy(qreg_0[0],qreg_0[2])
bindings = {param_0: -0.545000, param_1: -0.593000, }
main_circ = main_circ.assign_parameters(bindings)

print(Path(__file__).name, " results:")
main_circ.measure_active()
run_routing_simulation(main_circ, "1618")
