from qiskit import QuantumCircuit, QuantumRegister, ClassicalRegister
from qiskit.circuit import Parameter, ParameterVector
from helpers.qiskit_helpers import compare_statevectors, run_on_simulator, run_routing_simulation, run_pass_on_simulator
from pathlib import Path
from math import pi

main_circ = QuantumCircuit(4)
# Adding qregs 
qreg_0 = QuantumRegister(1)
main_circ.add_register(qreg_0)
# Adding creg resources 
creg_0 = ClassicalRegister(1)
main_circ.add_register(creg_0)
creg_1 = ClassicalRegister(1)
main_circ.add_register(creg_1)
# Adding symbols 
param_0 = Parameter("param_0")
param_1 = Parameter("param_1")
param_2 = Parameter("param_2")
param_3 = Parameter("param_3")
param_4 = Parameter("param_4")
param_5 = Parameter("param_5")

main_circ.cz(0,2)
main_circ.cz(3,2)
main_circ.y(2)
main_circ.cz(2,qreg_0[0])
main_circ.rz(param_1, qreg_0[0])
main_circ.cz(qreg_0[0],2)
main_circ.cy(1,2)
main_circ.cz(qreg_0[0],2)
main_circ.cz(1,qreg_0[0])
main_circ.cy(1,qreg_0[0])
main_circ.cz(3,1)
main_circ.y(1)
main_circ.cz(0,1)
main_circ.rz(param_3, 2)
main_circ.cz(qreg_0[0],2)
main_circ.cz(1,2)
main_circ.y(1)
main_circ.rz(-0.398000, qreg_0[0])
main_circ.rz(param_5, 2)
main_circ.cz(3,1)
main_circ.rz(-0.801000, 2)
main_circ.rz(-0.378000, qreg_0[0])
main_circ.rz(0.629000, 3)
main_circ.cz(qreg_0[0],2)
main_circ.cz(1,2)
main_circ.y(2)
main_circ.cz(qreg_0[0],2)
main_circ.y(qreg_0[0])
main_circ.cz(2,1)
main_circ.rz(param_4, 2)
main_circ.rz(0.555000, 1)
main_circ.cz(0,qreg_0[0])
main_circ.cy(0,3)
main_circ.cy(qreg_0[0],2)
main_circ.cy(0,2)
main_circ.cy(0,3)
main_circ.rz(param_1, 1)
main_circ.cy(1,qreg_0[0])
main_circ.cz(1,3)
main_circ.cz(0,3)
main_circ.rz(param_0, 3)
main_circ.rz(param_0, qreg_0[0])
main_circ.cz(2,0)
main_circ.rz(param_0, qreg_0[0])
main_circ.cy(2,qreg_0[0])
bindings = {param_0: 0.645000, param_1: -0.173000, param_3: -0.877000, param_4: 0.671000, param_5: 0.153000, }
main_circ = main_circ.assign_parameters(bindings)

print(Path(__file__).name, " results:")
compare_statevectors(main_circ, "InverseCancellation")
