from qiskit import QuantumCircuit, QuantumRegister, ClassicalRegister
from qiskit.circuit import Parameter, ParameterVector
from helpers.qiskit_helpers import compare_statevectors, run_on_simulator, run_routing_simulation, run_pass_on_simulator
from pathlib import Path
from math import pi

main_circ = QuantumCircuit(4)
# Adding qregs 
qreg_0 = QuantumRegister(1)
main_circ.add_register(qreg_0)
# Adding creg resources 
creg_0 = ClassicalRegister(1)
main_circ.add_register(creg_0)
creg_1 = ClassicalRegister(1)
main_circ.add_register(creg_1)
# Adding symbols 
param_0 = Parameter("param_0")
param_1 = Parameter("param_1")
param_2 = Parameter("param_2")
param_3 = Parameter("param_3")
param_4 = Parameter("param_4")

main_circ.z(1)
main_circ.cz(0,2)
main_circ.x(3)
main_circ.cx(2,3)
main_circ.cx(2,qreg_0[0])
main_circ.cx(2,0)
main_circ.cz(1,3)
main_circ.z(qreg_0[0])
main_circ.cx(0,1)
main_circ.x(1)
main_circ.cx(3,2)
main_circ.z(2)
main_circ.x(3)
main_circ.cz(3,qreg_0[0])
main_circ.cz(1,0)
main_circ.x(0)
main_circ.cx(3,qreg_0[0])
main_circ.x(qreg_0[0])
main_circ.x(0)
main_circ.z(0)
main_circ.x(3)
main_circ.cx(1,qreg_0[0])
main_circ.x(1)
main_circ.z(qreg_0[0])
main_circ.x(1)
main_circ.x(2)
main_circ.cx(0,qreg_0[0])
main_circ.x(1)
main_circ.x(2)
main_circ.z(2)
main_circ.cz(0,3)
main_circ.cx(0,2)
main_circ.cz(1,2)
main_circ.cz(2,qreg_0[0])
main_circ.z(qreg_0[0])
main_circ.cx(3,2)
main_circ.cx(qreg_0[0],2)
main_circ.z(qreg_0[0])
main_circ.cx(qreg_0[0],3)
main_circ.cz(3,qreg_0[0])
main_circ.cz(qreg_0[0],3)
main_circ.cz(1,0)
main_circ.z(2)
main_circ.x(3)
main_circ.cx(qreg_0[0],0)
main_circ.cz(0,3)
main_circ.cx(3,2)
main_circ.cz(qreg_0[0],3)
main_circ.cx(3,1)
main_circ.cx(qreg_0[0],0)
main_circ.cx(qreg_0[0],2)
main_circ.cx(3,2)
main_circ.z(2)
main_circ.cz(3,1)
main_circ.z(2)
main_circ.z(1)
bindings = {}
main_circ = main_circ.assign_parameters(bindings)

print(Path(__file__).name, " results:")
compare_statevectors(main_circ, "TemplateOptimization")
