from qiskit import QuantumCircuit, QuantumRegister, ClassicalRegister
from qiskit.circuit import Parameter, ParameterVector
from helpers.qiskit_helpers import compare_statevectors, run_on_simulator, run_routing_simulation, run_pass_on_simulator
from pathlib import Path
from math import pi

subcirc0 = QuantumCircuit(0)
# Adding qregs 
qreg_0 = QuantumRegister(4)
subcirc0.add_register(qreg_0)
# Adding creg resources 
subcirc0.cy(qreg_0[1],qreg_0[2])
subcirc0.z(qreg_0[3])
subcirc0.cy(qreg_0[1],qreg_0[0])
subcirc0.x(qreg_0[1])
subcirc0.x(qreg_0[3])
subcirc0 = subcirc0.to_gate().control(1)

subcirc1 = QuantumCircuit(0)
# Adding qregs 
qreg_0 = QuantumRegister(3)
subcirc1.add_register(qreg_0)
qreg_3 = QuantumRegister(1)
subcirc1.add_register(qreg_3)
# Adding creg resources 
subcirc1.z(qreg_3[0])
subcirc1.s(qreg_3[0])
subcirc1.z(qreg_0[2])
subcirc1.s(qreg_0[1])
subcirc1.x(qreg_0[2])
subcirc1 = subcirc1.to_gate().control(2)

main_circ = QuantumCircuit(0)
# Adding qregs 
qreg_0 = QuantumRegister(1)
main_circ.add_register(qreg_0)
qreg_1 = QuantumRegister(3)
main_circ.add_register(qreg_1)
# Adding creg resources 
creg_0 = ClassicalRegister(2)
main_circ.add_register(creg_0)
# Adding symbols 
param_0 = Parameter("param_0")
param_1 = Parameter("param_1")
param_2 = Parameter("param_2")

main_circ.x(qreg_1[1])
main_circ.s(qreg_1[0])
main_circ.z(qreg_1[1])
main_circ.s(qreg_1[2])
main_circ.cy(qreg_1[1],qreg_0[0])
main_circ.s(qreg_1[0])
main_circ.cy(qreg_1[0],qreg_1[2])
main_circ.cy(qreg_1[1],qreg_0[0])
main_circ.cy(qreg_1[1],qreg_1[2])
main_circ.x(qreg_1[0])
main_circ.cy(qreg_1[0],qreg_1[2])
main_circ.cy(qreg_1[2],qreg_1[1])
main_circ.s(qreg_1[1])
main_circ.cy(qreg_0[0],qreg_1[1])
main_circ.z(qreg_1[0])
main_circ.x(qreg_0[0])
main_circ.z(qreg_0[0])
main_circ.x(qreg_1[0])
main_circ.z(qreg_1[2])
main_circ.cy(qreg_0[0],qreg_1[1])
main_circ.z(qreg_0[0])
main_circ.z(qreg_1[2])
main_circ.s(qreg_1[0])
main_circ.s(qreg_0[0])
main_circ.cy(qreg_1[2],qreg_1[1])
main_circ.s(qreg_1[2])
main_circ.z(qreg_1[1])
main_circ.z(qreg_1[0])
main_circ.s(qreg_1[2])
main_circ.cy(qreg_0[0],qreg_1[0])
main_circ.x(qreg_0[0])
main_circ.z(qreg_1[0])
main_circ.cy(qreg_1[0],qreg_1[1])
main_circ.cy(qreg_1[2],qreg_1[0])
main_circ.cy(qreg_1[0],qreg_0[0])
main_circ.z(qreg_0[0])
main_circ.s(qreg_1[1])
main_circ.x(qreg_1[1])
main_circ.z(qreg_1[2])
main_circ.s(qreg_0[0])
main_circ.x(qreg_1[1])
main_circ.z(qreg_1[0])
main_circ.s(qreg_1[0])
main_circ.z(qreg_1[1])
main_circ.z(qreg_0[0])
bindings = {}
main_circ = main_circ.assign_parameters(bindings)

print(Path(__file__).name, " results:")
compare_statevectors(main_circ, "RemoveFinalReset")
