from qiskit import QuantumCircuit, QuantumRegister, ClassicalRegister
from qiskit.circuit import Parameter, ParameterVector
from helpers.qiskit_helpers import compare_statevectors, run_on_simulator, run_routing_simulation, run_pass_on_simulator
from pathlib import Path
from math import pi

subcirc0 = QuantumCircuit(0)
# Adding qregs 
qreg_0 = QuantumRegister(1)
subcirc0.add_register(qreg_0)
qreg_1 = QuantumRegister(2)
subcirc0.add_register(qreg_1)
qreg_3 = QuantumRegister(1)
subcirc0.add_register(qreg_3)
# Adding creg resources 
subcirc0.x(qreg_1[0])
subcirc0.cy(qreg_3[0],qreg_1[0])
subcirc0.cz(qreg_1[0],qreg_1[1])
subcirc0.cy(qreg_0[0],qreg_3[0])
subcirc0 = subcirc0.to_gate().control(2)

main_circ = QuantumCircuit(0)
# Adding qregs 
qreg_0 = QuantumRegister(2)
main_circ.add_register(qreg_0)
qreg_2 = QuantumRegister(1)
main_circ.add_register(qreg_2)
qreg_3 = QuantumRegister(1)
main_circ.add_register(qreg_3)
# Adding creg resources 
creg_0 = ClassicalRegister(2)
main_circ.add_register(creg_0)
# Adding symbols 
param_0 = Parameter("param_0")
param_1 = Parameter("param_1")

main_circ.cy(qreg_2[0],qreg_0[0])
main_circ.cy(qreg_0[1],qreg_3[0])
main_circ.cy(qreg_3[0],qreg_0[1])
main_circ.cz(qreg_3[0],qreg_2[0])
main_circ.cz(qreg_0[0],qreg_2[0])
main_circ.rx(param_1, qreg_0[1])
main_circ.cz(qreg_0[0],qreg_3[0])
main_circ.cz(qreg_3[0],qreg_2[0])
main_circ.cy(qreg_0[1],qreg_2[0])
main_circ.rx(0.577000, qreg_0[1])
main_circ.cz(qreg_3[0],qreg_0[1])
main_circ.x(qreg_0[1])
main_circ.x(qreg_0[1])
main_circ.cy(qreg_0[1],qreg_3[0])
main_circ.x(qreg_0[0])
main_circ.x(qreg_0[1])
main_circ.rx(param_1, qreg_3[0])
main_circ.cy(qreg_0[0],qreg_3[0])
main_circ.cy(qreg_0[1],qreg_3[0])
main_circ.cy(qreg_0[1],qreg_3[0])
main_circ.x(qreg_2[0])
main_circ.cz(qreg_0[0],qreg_0[1])
main_circ.rx(-0.513000, qreg_3[0])
main_circ.cy(qreg_2[0],qreg_0[1])
main_circ.cz(qreg_0[0],qreg_0[1])
main_circ.cz(qreg_3[0],qreg_0[1])
main_circ.x(qreg_0[1])
main_circ.cz(qreg_0[1],qreg_0[0])
main_circ.x(qreg_2[0])
main_circ.cz(qreg_2[0],qreg_3[0])
main_circ.x(qreg_2[0])
main_circ.cy(qreg_3[0],qreg_0[0])
main_circ.x(qreg_0[0])
main_circ.cy(qreg_2[0],qreg_0[1])
main_circ.cz(qreg_0[0],qreg_0[1])
main_circ.x(qreg_3[0])
main_circ.x(qreg_3[0])
main_circ.rx(-0.410000, qreg_2[0])
main_circ.rx(param_0, qreg_0[1])
main_circ.rx(0.775000, qreg_2[0])
main_circ.cz(qreg_2[0],qreg_3[0])
main_circ.x(qreg_0[1])
main_circ.rx(-0.286000, qreg_2[0])
bindings = {param_0: 0.093000, param_1: 0.931000, }
main_circ = main_circ.assign_parameters(bindings)

print(Path(__file__).name, " results:")
compare_statevectors(main_circ, "CollectCliffords")
