from qiskit import QuantumCircuit, QuantumRegister, ClassicalRegister
from qiskit.circuit import Parameter, ParameterVector
from helpers.qiskit_helpers import compare_statevectors, run_on_simulator, run_routing_simulation, run_pass_on_simulator
from pathlib import Path
from math import pi

subcirc0 = QuantumCircuit(0)
# Adding qregs 
qreg_0 = QuantumRegister(3)
subcirc0.add_register(qreg_0)
qreg_3 = QuantumRegister(1)
subcirc0.add_register(qreg_3)
# Adding creg resources 
subcirc0.rx(0.729000, qreg_0[2])
subcirc0.z(qreg_3[0])
subcirc0.z(qreg_0[0])
subcirc0.cx(qreg_0[0],qreg_0[2])
subcirc0.y(qreg_3[0])
subcirc0.z(qreg_3[0])
subcirc0 = subcirc0.to_gate().control(1)

main_circ = QuantumCircuit(0)
# Adding qregs 
qreg_0 = QuantumRegister(3)
main_circ.add_register(qreg_0)
qreg_3 = QuantumRegister(1)
main_circ.add_register(qreg_3)
# Adding creg resources 
creg_0 = ClassicalRegister(2)
main_circ.add_register(creg_0)
# Adding symbols 
param_0 = Parameter("param_0")
param_1 = Parameter("param_1")

main_circ.rx(0.567000, qreg_0[2])
main_circ.y(qreg_0[1])
main_circ.y(qreg_3[0])
main_circ.z(qreg_0[1])
main_circ.z(qreg_0[2])
main_circ.z(qreg_0[0])
main_circ.z(qreg_0[1])
main_circ.cx(qreg_3[0],qreg_0[1])
main_circ.rx(-0.601000, qreg_0[0])
main_circ.z(qreg_0[1])
main_circ.z(qreg_0[2])
main_circ.cx(qreg_0[0],qreg_0[1])
main_circ.rx(0.637000, qreg_3[0])
main_circ.rx(-0.257000, qreg_3[0])
main_circ.rx(param_1, qreg_0[1])
main_circ.y(qreg_0[0])
main_circ.y(qreg_3[0])
main_circ.z(qreg_0[0])
main_circ.rx(0.444000, qreg_3[0])
main_circ.y(qreg_3[0])
main_circ.z(qreg_0[0])
main_circ.y(qreg_0[0])
main_circ.cx(qreg_0[1],qreg_0[2])
main_circ.cx(qreg_0[1],qreg_3[0])
main_circ.z(qreg_0[1])
main_circ.rx(param_1, qreg_0[0])
main_circ.z(qreg_0[2])
main_circ.z(qreg_0[2])
main_circ.z(qreg_3[0])
main_circ.y(qreg_0[0])
main_circ.cx(qreg_0[2],qreg_0[0])
main_circ.cx(qreg_0[2],qreg_0[1])
main_circ.cx(qreg_0[1],qreg_0[0])
main_circ.cx(qreg_3[0],qreg_0[1])
main_circ.cx(qreg_0[2],qreg_3[0])
main_circ.cx(qreg_0[1],qreg_3[0])
main_circ.cx(qreg_3[0],qreg_0[1])
main_circ.cx(qreg_3[0],qreg_0[2])
main_circ.rx(-0.271000, qreg_0[2])
main_circ.y(qreg_0[1])
main_circ.rx(param_1, qreg_0[2])
main_circ.rx(param_0, qreg_0[0])
main_circ.cx(qreg_0[1],qreg_0[0])
bindings = {param_0: -0.897000, param_1: 0.483000, }
main_circ = main_circ.assign_parameters(bindings)

print(Path(__file__).name, " results:")
compare_statevectors(main_circ, "HoareOptimizer")
