from qiskit import QuantumCircuit, QuantumRegister, ClassicalRegister
from qiskit.circuit import Parameter, ParameterVector
from helpers.qiskit_helpers import compare_statevectors, run_on_simulator, run_routing_simulation, run_pass_on_simulator
from pathlib import Path
from math import pi

main_circ = QuantumCircuit(0)
# Adding qregs 
qreg_0 = QuantumRegister(2)
main_circ.add_register(qreg_0)
qreg_2 = QuantumRegister(2)
main_circ.add_register(qreg_2)
# Adding creg resources 
creg_0 = ClassicalRegister(2)
main_circ.add_register(creg_0)
# Adding symbols 
param_0 = Parameter("param_0")
param_1 = Parameter("param_1")
param_2 = Parameter("param_2")

main_circ.x(qreg_0[1])
main_circ.cx(qreg_0[1],qreg_2[1])
main_circ.cy(qreg_0[1],qreg_2[1])
main_circ.x(qreg_0[1])
main_circ.cy(qreg_0[1],qreg_2[1])
main_circ.cx(qreg_0[0],qreg_2[1])
main_circ.cy(qreg_2[0],qreg_2[1])
main_circ.x(qreg_0[0])
main_circ.cx(qreg_2[1],qreg_2[0])
main_circ.x(qreg_2[0])
main_circ.rx(param_1, qreg_0[0])
main_circ.cx(qreg_0[1],qreg_0[0])
main_circ.x(qreg_2[1])
main_circ.rx(param_0, qreg_2[0])
main_circ.x(qreg_2[1])
main_circ.rx(0.437000, qreg_0[1])
main_circ.cx(qreg_2[0],qreg_0[0])
main_circ.cy(qreg_0[1],qreg_0[0])
main_circ.x(qreg_2[0])
main_circ.x(qreg_2[0])
main_circ.cx(qreg_0[0],qreg_2[1])
main_circ.cx(qreg_2[1],qreg_0[0])
main_circ.x(qreg_2[0])
main_circ.cy(qreg_0[1],qreg_2[0])
main_circ.cx(qreg_2[1],qreg_2[0])
main_circ.x(qreg_0[1])
main_circ.x(qreg_2[0])
main_circ.rx(-0.277000, qreg_0[0])
main_circ.rx(param_2, qreg_2[1])
main_circ.cy(qreg_2[0],qreg_2[1])
main_circ.cx(qreg_2[1],qreg_0[1])
main_circ.x(qreg_2[0])
main_circ.rx(param_2, qreg_2[0])
main_circ.cx(qreg_0[1],qreg_2[0])
main_circ.cy(qreg_2[0],qreg_0[1])
main_circ.cy(qreg_0[1],qreg_2[0])
main_circ.cy(qreg_0[0],qreg_0[1])
main_circ.x(qreg_2[1])
main_circ.cx(qreg_0[0],qreg_2[1])
main_circ.x(qreg_2[0])
main_circ.cy(qreg_0[0],qreg_0[1])
main_circ.rx(param_0, qreg_2[1])
main_circ.cy(qreg_0[1],qreg_2[0])
main_circ.x(qreg_2[1])
main_circ.cy(qreg_2[1],qreg_0[1])
main_circ.rx(0.079000, qreg_2[0])
main_circ.x(qreg_2[1])
main_circ.cx(qreg_0[1],qreg_2[1])
main_circ.cy(qreg_0[0],qreg_2[0])
main_circ.x(qreg_0[1])
main_circ.rx(param_1, qreg_2[0])
main_circ.cx(qreg_0[0],qreg_0[1])
main_circ.rx(param_2, qreg_2[0])
main_circ.cx(qreg_2[0],qreg_0[1])
main_circ.cy(qreg_0[0],qreg_2[1])
main_circ.cx(qreg_0[0],qreg_2[1])
main_circ.cx(qreg_0[1],qreg_2[0])
main_circ.cy(qreg_2[1],qreg_2[0])
main_circ.x(qreg_0[0])
main_circ.cy(qreg_2[1],qreg_0[1])
bindings = {param_0: -0.956000, param_1: 0.164000, param_2: 0.005000, }
main_circ = main_circ.assign_parameters(bindings)

print(Path(__file__).name, " results:")
main_circ.measure_active()
run_routing_simulation(main_circ, "684")
