from qiskit import QuantumCircuit, QuantumRegister, ClassicalRegister
from qiskit.circuit import Parameter, ParameterVector
from helpers.qiskit_helpers import compare_statevectors, run_on_simulator, run_routing_simulation, run_pass_on_simulator
from pathlib import Path
from math import pi

main_circ = QuantumCircuit(2)
# Adding qregs 
qreg_0 = QuantumRegister(4)
main_circ.add_register(qreg_0)
# Adding creg resources 
creg_0 = ClassicalRegister(1)
main_circ.add_register(creg_0)
creg_1 = ClassicalRegister(1)
main_circ.add_register(creg_1)
# Adding symbols 
param_0 = Parameter("param_0")
param_1 = Parameter("param_1")
param_2 = Parameter("param_2")
param_3 = Parameter("param_3")

main_circ.cz(0,1)
main_circ.x(qreg_0[2])
main_circ.u(0,param_0,-0.633000, qreg_0[0])
main_circ.cz(qreg_0[3],qreg_0[0])
main_circ.cz(1,qreg_0[2])
main_circ.u(param_2,param_0,param_0, 0)
main_circ.cz(0,qreg_0[1])
main_circ.x(qreg_0[1])
main_circ.s(qreg_0[3])
main_circ.x(qreg_0[3])
main_circ.s(0)
main_circ.u(0,param_1,-0.590000, qreg_0[1])
main_circ.x(qreg_0[3])
main_circ.x(qreg_0[0])
main_circ.cz(1,0)
main_circ.cz(qreg_0[2],1)
main_circ.x(qreg_0[2])
main_circ.cz(0,qreg_0[3])
main_circ.cz(qreg_0[2],0)
main_circ.s(qreg_0[2])
main_circ.u(param_2,param_1,param_1, qreg_0[0])
main_circ.s(qreg_0[1])
main_circ.x(qreg_0[3])
main_circ.u(0,param_2,param_3, qreg_0[1])
main_circ.s(qreg_0[3])
main_circ.s(1)
main_circ.x(qreg_0[0])
main_circ.u(0,param_2,param_3, qreg_0[0])
main_circ.u(0,0,-0.018000, 0)
main_circ.s(1)
main_circ.x(qreg_0[3])
main_circ.u(param_0,param_0,param_2, qreg_0[1])
main_circ.x(1)
main_circ.s(qreg_0[3])
main_circ.cz(1,qreg_0[2])
main_circ.cz(qreg_0[2],0)
main_circ.cz(qreg_0[3],qreg_0[0])
main_circ.cz(0,1)
main_circ.cz(qreg_0[3],0)
main_circ.cz(qreg_0[0],qreg_0[1])
main_circ.u(0,param_2,-0.158000, qreg_0[3])
main_circ.cz(qreg_0[1],qreg_0[0])
main_circ.x(qreg_0[2])
main_circ.cz(qreg_0[0],0)
main_circ.s(1)
main_circ.cz(qreg_0[1],qreg_0[0])
main_circ.cz(0,qreg_0[3])
main_circ.u(param_2,param_1,-0.172000, qreg_0[3])
bindings = {param_0: 0.814000, param_1: -0.362000, param_2: 0.687000, param_3: 0.713000, }
main_circ = main_circ.assign_parameters(bindings)

print(Path(__file__).name, " results:")
main_circ.measure_active()
run_routing_simulation(main_circ, "525")
